### ISSUE TITLE
Language admin

### ISSUE THREAD

**Issue by roman5527** [sniggle/joomla-bootstrap4-template#13]
Hi, I install 1.8 version template and i see it : http://prntscr.com/j257el

i think languge files dont copy to admin language folder.

**Comment by roman5527** [comment]
And frontend too : http://prntscr.com/j2599e

**Comment by jwiesel** [comment]
Hi @roman5527 ,
I'm sorry to hear that. I just did some tests myself. For me the installation works in en-GB and also in de-DE. Does it work for you in en-GB?
You can change the language of your admin-user and install the template again to see, if the translation works. In general Joomla uses for front-end-sys-ini-file for the installation. In our case: "/language/en-GB/en-GB.tpl_bootstrap4.sys.ini" For the frontend elements (e.g. BacktoTop) the normal .ini. You can also check, if the files are correctly uploaded.
Did you customize the template after downloading? If so: There are certain pitfalls, you can check: https://stackoverflow.com/questions/19284995/joomla-template-language - e.g. if the <name> of the template has been changed by you, the language files have to follow the same pattern as well. Otherwise joomla will not load them. This includes small and capital letters.

**Comment by roman5527** [comment]
Hello, thanks i change any file . I fix it . It ok . can you close .
