### ISSUE TITLE
no drop down menu

### ISSUE THREAD

**Issue by josflachs** [sniggle/joomla-bootstrap4-template#2]
Hi, I've installed your template. I noticed the dropdown menu doesn't work. Only the top lever links are shown. Nothing else.

**Comment by jwiesel** [comment]
Hi, thanks for reporting this issue! I just upgraded to the latest bootstrap version and fixed it. In version 1.3 it should work.

**Comment by josflachs** [comment]
Works! 
But ... You need the reaction speed of an astronaut to click the underlying links. ;-)
I made 1 lower level link. Can't click it in time. 
The menu is vertical. How do I get horizontal?

**Comment by jwiesel** [comment]
Hi @josflachs,
did you install and activate our plugin to disable bootstrap 2? You can find it here: https://github.com/sniggle/joomla-disable-jui-bootstrap
I had the same issue without the plugin as the two bootstrap versions produce some conflicts, when running at the same time.

For styling: You can use bootstrap 4 classes as "Menu Class Suffix" to change the menu styles under "Module settings > Advanced".
Demo page: https://theaterverein-mastershausen.de/ueber-uns/beitritt
Examples - important: don't forget the leading blank!:
* Navbar: " navbar-nav mr-auto"
* Sidebar: " nav nav-pills flex-column"
* Footer: " nav flex-column"

Further styling options can be found here: https://v4-alpha.getbootstrap.com/components/navs/
Hope that helps!

**Comment by josflachs** [comment]
Hi Wiesel,

What's your first name? 

Works!
Still one issue: with your plugin and the added navbar css it works perfect. But now the top menu link no longer works. It functions only to show the menu items under it.  
I know some extension rely heavily on the Bootstrap 2 framework I just deactivated. Will that create problems in the future?

**Comment by jwiesel** [comment]
Hi,
I think what you are referring to is a general design concept in bootstrap. Dropdowns here only act like them as they have to be clicked rather than hovered like in Joomla JUI. (see https://getbootstrap.com/docs/4.0/components/navbar/#nav ). You can solve this by adding content behind the parent and adding a breadcrumb. By that a user can "go up" one page to the parent. As the parent page gets somewhat hidden, I would move the most important content down to a child-page.
Regarding bootstrap 2 and bootstrap 4: It could cause problems with existing extensions. In my projects I was lucky so far as the method names did not change.
For the future: The joomla-project is moving towards Bootstrap 4 :) https://developer.joomla.org/news/658-joomla4-manifesto.html (at least that was the plan 1 year ago) Therefore I could imagine that possible problems will get less.
