### ISSUE TITLE
Menu sub-menu items do not display

### ISSUE THREAD

**Issue by Scrabble96** [sniggle/joomla-bootstrap4-template#9]
I have installed the template and created two new single-article menu items which are children of a main menu item 'About'. I have not changed or added any code in the template.

The menu displays with a drop-down icon but does not open to reveal the child items, either when hovering on clicking with a mouse on a desktop, or with a tap on a Samsung smartphone or my iPad.

I have seen similar closed issues on this subject and I have installed "joomla-disable-jui-bootstrap-master.zip" but it makes no difference, even after enabling the Plugin. Examining the site at gtmetrix.com shows that several files are still being loaded from the /media/jui folder:

![image](https://user-images.githubusercontent.com/36987494/36908460-316fb17c-1e33-11e8-9065-7a2078a70895.png)

I can't see if the plugin is working on the theaterverein-mastershausen.de website as they're using JCH Optimize.

**Comment by Scrabble96** [comment]
Update on the drop-down menu issue above:

1. I had created the dropdown header menu item using Joomla's item type of "Separator". It doesn't work.
2. I tried again using the menu item type "Menu heading". That doesn't work, either.
3. I changed the item type to "Single article" and created a blank article. It works!

**Comment by jwiesel** [comment]
Hi @Scrabble96 , I just checked the issue.
I guess using a separator as menu entry is not intentional.
I think the solution you found makes perfect sense for different reasons. (e.g. via breadcrumbs you can now navigate to the parent article of a section of your site)
Anyhow I realized, that the dropdown separator was not working correctly. I just fixed that. Will be part of the next version.

**Comment by jwiesel** [comment]
fixed in release 1.8
